#!/home/robopy/ros2_venv/bin/python3
import os
import sys
import importlib.util

# Percorso del modulo reale
MODULE_PATH = "/mnt/ssd/robopy_controller_host/robopy_controller/nodes/respeaker_vui_node.py"

try:
    spec = importlib.util.spec_from_file_location("module", MODULE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
except Exception as e:
    print(f"Error loading respeaker_vui_node: {e}")
    sys.exit(1)

if __name__ == '__main__':
    module.main()
